---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: server-amazonlinux
          suite: server-amazonlinux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-centos-6
          suite: server-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-centos-7
          suite: server-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-debian-8
          suite: server-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-debian-9
          suite: server-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-ubuntu-1604
          suite: server-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-ubuntu-1804
          suite: server-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-verification-ubuntu-1604
          suite: server-verification-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: server-verify-no-databag-ubuntu-1604
          suite: server-verify-no-databag-ubuntu-1604
          requires: *lint_and_unit
